add_rules("mode.debug", "mode.release")
add_rules("plugin.compile_commands.autoupdate", {outputdir = ".vscode"})
set_languages("c++23")
set_project("ZeitKert")
set_version("0.1")
add_includedirs("src")
set_toolchains("clang")

add_requires("linenoise", "simdjson", "rapidjson", "gtest", "fmt 12.1.0",
             "spdlog v1.17.0", "xxhash")

target("libzeitkert")
    set_kind("static")
    add_files("src/**.cpp|main.cpp")
    add_packages("linenoise", "simdjson", "rapidjson", "fmt", "spdlog", "xxhash")

target("libzeitkert_test")
    set_kind("static")
    add_defines("TESTS")
    add_rules("mode.debug")
    add_files("src/**.cpp|main.cpp")
    add_packages("linenoise", "simdjson", "rapidjson", "fmt", "spdlog", "xxhash")

target("ZeitKert")
    set_kind("binary")
    add_files("src/main.cpp")
    add_deps("libzeitkert")
    add_packages("linenoise", "simdjson", "rapidjson", "fmt", "spdlog", "xxhash")

target("tests")
    set_kind("binary")
    add_cxxflags("-DTESTS")
    add_files("tests/**.cpp")
    add_deps("libzeitkert_test")
    add_syslinks("asan")
    add_rules("mode.debug")
    add_cxxflags("-fsanitize=address", "-fno-omit-frame-pointer")
    add_packages("linenoise", "simdjson", "rapidjson", "gtest", "fmt", "spdlog",
                 "xxhash")

target("bpm-bench")
    set_kind("binary")
    -- add_cxxflags("-DTESTS")
    add_files("benchmark/bpm-bench.cpp")
    add_deps("libzeitkert")
    add_rules("mode.debug")
    add_packages("linenoise", "simdjson", "rapidjson", "fmt", "spdlog", "xxhash")

target("sqltest")
    set_kind("binary")
    add_files("tools/sqltest/SQLTest.cpp")
    add_deps("libzeitkert")
    add_rules("mode.debug")
    add_packages("linenoise", "simdjson", "rapidjson", "fmt", "spdlog", "xxhash")

set_default("ZeitKert")
